[package]
name = "silius-builder"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
anyhow.workspace = true
async-trait.workspace = true

# silius dependencies
silius-chain.workspace = true
silius-primitives.workspace = true
silius-wallet.workspace = true
