[workspace]
default-members = ["bin/silius"]
members = [
    "bin/silius",
    "crates/builder",
    "crates/chain",
    "crates/executor",
    "crates/manager",
    "crates/mempool",
    "crates/network",
    "crates/node/builder",
    "crates/node/manager",
    "crates/node/version",
    "crates/primitives",
    "crates/rpc",
    "crates/storage",
    "crates/validation",
    "crates/wallet",
    # "bin/silius",
    # "crates/bundler",
    # "crates/contracts",
    # "crates/grpc",
    # "crates/mempool",
    # "crates/p2p",
    # "crates/primitives",
    # "crates/rpc",
    # "examples/*",
    # "tests",
]
resolver = "2"
# exclude = ["book/cli", "book/sources"]

[workspace.package]
authors = ["https://github.com/silius-rs/silius/graphs/contributors"]
edition = "2024"
keywords = [
    "ethereum",
    "account abstraction",
    "erc-4337",
    "bundler",
    "blockchain",
    "protocol",
    "silius",
]
license = "MIT OR Apache-2.0"
homepage = "https://silius.rs"
repository = "https://github.com/silius-rs/silius"
rust-version = "1.87.0"
version = "0.6.0"

[workspace.dependencies]
actix-web = "4.10.2"
actix-ws = "0.3.0"
alloy-consensus = { version = "1.0.12" }
alloy-contract = { version = "1.0.9" }
alloy-eips = { version = "1.0.12", features = ["serde"] }
alloy-network = { version = "1.0.12" }
alloy-primitives = { version = "1.1.0", features = ["serde"] }
alloy-provider = { version = "1.0.9", features = ["pubsub", "ws"] }
alloy-rpc-types-eth = { version = "1.0.12" }
alloy-signer-local = { version = "1.0.9", features = ["mnemonic"] }
alloy-sol-types = { version = "1.1.0", features = ["json"] }
anyhow = "1.0"
async-trait = "0.1.86"
bincode = { version = "2.0.1", features = ["serde"] }
clap = "4"
directories = { version = "6.0.0" }
futures = "0.3"
futures-util = "0.3.31"
home = "0.5.11"
parking_lot = "0.12.3"
redb = { version = "2.4.0" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0.139"
serde_yaml = "0.9"
tempfile = "3.19"
thiserror = "2.0.11"
tokio = { version = "1.42", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "signal",
    "time",
    "macros",
] }
tokio-util = { version = "0.7", features = ["compat"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# silius dependencies
silius-builder = { path = "crates/builder" }
silius-chain = { path = "crates/chain" }
silius-executor = { path = "crates/executor" }
silius-manager = { path = "crates/manager" }
silius-mempool = { path = "crates/mempool" }
silius-network = { path = "crates/network" }
silius-node-builder = { path = "crates/node/builder" }
silius-node-manager = { path = "crates/node/manager" }
silius-node-version = { path = "crates/node/version" }
silius-primitives = { path = "crates/primitives" }
silius-rpc = { path = "crates/rpc" }
silius-storage = { path = "crates/storage" }
silius-validation = { path = "crates/validation" }
silius-wallet = { path = "crates/wallet" }

# # workspace crates
# silius-bundler = { version = "0.5.0-alpha", path = "crates/bundler", default-features = false }
# silius-contracts = { version = "0.5.0-alpha", path = "crates/contracts", default-features = false }
# silius-grpc = { version = "0.5.0-alpha", path = "crates/grpc", default-features = false }
# silius-mempool = { version = "0.5.0-alpha", path = "crates/mempool", default-features = false }
# silius-metrics = { version = "0.5.0-alpha", path = "crates/metrics", default-features = false }
# silius-p2p = { version = "0.5.0-alpha", path = "crates/p2p", default-features = false }
# silius-primitives = { version = "0.5.0-alpha", path = "crates/primitives", default-features = false }
# silius-rpc = { version = "0.5.0-alpha", path = "crates/rpc", default-features = false }
# silius-tests = { version = "0.5.0-alpha", path = "tests", default-features = false }

# # eth
# alloy-chains = "0.1.14"
# discv5 = { version = "0.4.0", features = ["libp2p"] }
# ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "5394d899adca736a602e316e6f0c06fdb5aa64b9", features = [
#     "ws",
# ] }
# ssz_rs = { git = "https://github.com/ralexstokes/ssz-rs.git", rev = "8640128ec83071094d24fb4511147d6b9dd029bb" }
# ssz_rs_derive = { git = "https://github.com/ralexstokes/ssz-rs.git", rev = "8640128ec83071094d24fb4511147d6b9dd029bb" }

# # async
# async-stream = "0.3.5"
# async-trait = "0.1.76"
# futures = "0.3.30"
# futures-util = "0.3.30"
# parking_lot = "0.12.1"

# # tokio
# tokio = { version = "1.35", features = ["full"] }

# # misc
# expanded-pathbuf = "0.1.2"
# eyre = "0.6.11"
# jsonrpsee = { version = "0.21.0", features = ["server", "macros", "client"] }
# metrics = "0.22.0"
# reqwest = { version = "0.11.4", features = ["json"] }
# lazy_static = "1.4.0"
# serde = "1.0.193"
# serde_json = "1.0.109"
# tempfile = "3.13.0"
# thiserror = "1.0.53"
# tracing = "0.1.40"

# [patch]
# [patch.crates-io]
# revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "3d8ca6641d2e72448c23f4596f769c8fd1c784d1" }
# [patch."https://github.com/gakonst/ethers-rs"]
# ethers = { git = "https://github.com/Vid201/ethers-rs", branch = "feat/patch" }
