[package]
name = "silius-validator"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-provider.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-trace.workspace = true
anyhow.workspace = true
async-trait.workspace = true
revm-bytecode.workspace = true
thiserror.workspace = true

# silius dependencies
silius-chain.workspace = true
silius-primitives.workspace = true
silius-storage.workspace = true
