[package]
name = "silius-mempool"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true

# silius dependencies
silius-primitives.workspace = true
silius-storage.workspace = true
silius-validator.workspace = true
