[package]
name = "silius-rpc"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
actix-web.workspace = true
actix-ws.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
futures-util.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true

# silius dependencies
silius-manager.workspace = true
silius-node-version.workspace = true
silius-primitives.workspace = true
